const sampleListings=[
  {
    title: "Beautiful Beach House",
    description: "A stunning beach house with ocean views.",
    images: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    location: "Malibu, CA",
    price: 500,
    country: "USA",
  },
  {
    title: "Mountain Cabin Retreat",
    description: "Cozy cabin surrounded by pine trees and fresh air.",
    images: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    location: "Aspen, CO",
    price: 300,
    country: "USA",
  },
  {
    title: "Modern City Apartment",
    description: "Stylish apartment in the heart of downtown.",
    images: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    location: "New York, NY",
    price: 700,
    country: "USA",
  },
  {
    title: "Lakefront Cottage",
    description: "Quiet cottage with direct lake access and stunning sunsets.",
    images: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    location: "Lake Tahoe, CA",
    price: 400,
    country: "USA",
  },
  {
    title: "Desert Villa",
    description: "Luxury villa with pool in the middle of the desert.",
    images: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    location: "Phoenix, AZ",
    price: 450,
    country: "USA",
  },
  {
    title: "Forest Treehouse",
    description: "Unique treehouse experience in the middle of a forest.",
    images: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    location: "Portland, OR",
    price: 350,
    country: "USA",
  },
  {
    title: "Countryside Farmhouse",
    description: "Charming farmhouse surrounded by green fields.",
    images: "https://images.unsplash.com/photo-1472220625704-91e1462799b2",
    location: "Vermont, USA",
    price: 250,
    country: "USA",
  },
{
    title: "Beautiful Beach House",
    description: "A stunning beach house with ocean views.",
    images: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    location: "Malibu, CA",
    price: 500,
    country: "USA",
  },
  {
    title: "Mountain Cabin Retreat",
    description: "Cozy cabin surrounded by pine trees and fresh air.",
    images: "https://images.unsplash.com/photo-1501785888041-af3ef285b470",
    location: "Aspen, CO",
    price: 300,
    country: "USA",
  },
  {
    title: "Modern City Apartment",
    description: "Stylish apartment in the heart of downtown.",
    images: "https://images.unsplash.com/photo-1502673530728-f79b4cab31b1",
    location: "New York, NY",
    price: 700,
    country: "USA",
  },
  {
    title: "Lakefront Cottage",
    description: "Quiet cottage with direct lake access and stunning sunsets.",
    images: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    location: "Lake Tahoe, CA",
    price: 400,
    country: "USA",
  },
  {
    title: "Desert Villa",
    description: "Luxury villa with pool in the middle of the desert.",
    images: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c",
    location: "Phoenix, AZ",
    price: 450,
    country: "USA",
  },
  {
    title: "Forest Treehouse",
    description: "Unique treehouse experience in the middle of a forest.",
    images: "https://images.unsplash.com/photo-1505691938895-1758d7feb511",
    location: "Portland, OR",
    price: 350,
    country: "USA",
  },
  {
    title: "Countryside Farmhouse",
    description: "Charming farmhouse surrounded by green fields.",
    images: "https://images.unsplash.com/photo-1472220625704-91e1462799b2",
    location: "Vermont, USA",
    price: 250,
    country: "USA",
  },
];
module.exports={data: sampleListings};